trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: pip install pytest
  displayName: 'Install pytest'

- script: pytest
  displayName: 'Run tests'

